[package]
name = "staple-cli"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
staple-workspace-hack = { version = "0.1", path = "../staple-workspace-hack" }
